### ISSUE TITLE
Gama shutdown immediately all time I run Moving 3D Object model

### ISSUE THREAD

**Issue by DAVIEPHAM** [gama-platform/gama.old#3398]
**Describe the bug**
Gama always shutdown when I run Moving 3D Object model (3D Visualization) and wrong output in headless mode.
I found the problem at line 34.
**Screenshots**
![image](https://user-images.githubusercontent.com/83625165/167284159-21a5fa4d-495e-410c-b6ba-6cd752113e9a.png)

**Comment by ptaillandier** [comment]
It is due to the GPU used (Radeon) which can have problems with opengl displays. It is not possible to fix this issue. The best solution is to specific the use of another GPU for GAMA (or to use a Java2D display). I added information about this bug in the [Troubleshouting](https://github.com/gama-platform/gama/wiki/Troubleshooting#problem-with-some-radeon-graphics-cards-and-opengl-display) section of the Documentation.

**Comment by AlexisDrogoul** [comment]
The reason was a bad configuration of GAMA as well.

**Comment by hqnghi88** [comment]
With my experience of using insider windows (developer versions), there is a restricted rule somewhere of windows, which is prevent the activation/using of GPU or event switching from integrated card (intel Hd, radeon) to GPU (nvidia) so it crashed immediately when gama initialize opengl.
The workaround i did is declare explicitly that the applications (java, javaw, eclipse and gama) always use extern GPU windows Settings / Display/ Graphics:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/6105384/167346645-ab193415-150d-4958-aa72-d51fe569f917.png">
<img width="342" alt="image" src="https://user-images.githubusercontent.com/6105384/167346696-2a080095-3469-40ff-b30f-7ca21e8db57a.png">
