### ISSUE TITLE
A goto problem with a small angle path

### ISSUE THREAD

**Issue by lgten1** [gama-platform/gama.old#3419]
BUG:
If goto on the path with a small angle,  it cannot reach the end point .It loops somewhere in the middle.

Here is my test code:

```
species a skills:[moving]{
	geometry shape <- rectangle(5, 5);
	point movetarget<-{6,1};
	geometry movepath<-smooth(line([location,{1,20},{5,40},movetarget]),0);
	reflex move{
		do goto target:movetarget speed:20#km/#h on:movepath;
	}
	aspect default {
		draw rectangle(5, 5) rotate:90 + heading color: #chocolate;
		draw movepath color: #orange ;
	}
}

experiment name type: gui {
	init{
		create a with:[location:{0,0}];
	}
	output {
		display my_display name:"show" {
			species a;
		}
	}
}
```

![1652404085125202251398581](https://user-images.githubusercontent.com/91418750/168191547-5559489c-959a-4300-95e4-c847a54b6cff.gif)

I alse test with a bigger angle:
![16524048029372022513920322](https://user-images.githubusercontent.com/91418750/168192747-d8815d70-73db-4e6b-8ec5-dfe2d0855a19.gif)

If i do not set `geometry shape <- rectangle(5, 5);`, it can goto the end point.

**Comment by ptaillandier** [comment]
Hi,

The problem was due to the fact that the agent had a polygonal
geometry. When gama updates the location of a polygon, it is possible that
due to rounding problems this location is not exactly the same as the
supposed one. In the moving skill, if the location is not the one supposed,
GAMA recomputes the path.... and in a case like this one, recomputing the
path can lead to a change of path :) .

I pushed a fix (but for GAMA 1.8.2). It will be available in the next
release. Note that if you comment the line "geometry shape <- rectangle(5,
5);" it works well.

Cheers,

Patrick
