### ISSUE TITLE
Missing GAMA logo on application shortcut on windows

### ISSUE THREAD

**Issue by LBIRE** [gama-platform/gama.old#3423]
**Is your request related to a problem? Please describe.**
When opening the shortcut interface on windows, the GAMA logo doesn't appear on the executable icon. However when launched, the logo appears normally on the spot bar. 

**Describe the improvement you'd like**
I would like to see the GAMA logo appear on the windows shortcut panel. 

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/104968829/168512673-40c8ea08-20ff-4135-b089-49d0c50cc549.png)

**Comment by lesquoyb** [comment]
I added a few icons in the `icon.ico` file (for some reason it seems that 8 bit versions are also required) and it seems to work after compilation. To be tested with the next release

**Comment by lesquoyb** [comment]
More infos: adding the 8 bit icons did fix the icon of the `gama.exe` file. However, for some reason the shortcut created in the installation process still has a blank icon. 
If we create the shortcut manually by right clicking on the `gama.exe` file, then the shortcut has the correct icon. 
What is even stranger is that the installer itself has the correct icon, and once installed, the `.gaml` files are showed with a correct icon too, which is described in the installer script. Therefore I don't think it is a problem of wrong path in the installation script or anything related.
I also noticed that the splash screen has the same "blank icon" showing in the taskbar, so the problem is probably in the definition of the icon of the splash screen

**Comment by hqnghi88** [comment]
Somewhere in the setup script i think. because when you go to properties of Gama shortcut on desktop, click on CHANGE ICON, it say cant find....
<img width="428" alt="image" src="https://user-images.githubusercontent.com/6105384/174618190-788f5ebd-f0a1-42f7-88d0-024aa5ec7216.png">
where a right path should point to the gama.exe . ie. for zalo, it point to right zalo.exe path
<img width="278" alt="image" src="https://user-images.githubusercontent.com/6105384/174618437-2bff1af5-83c5-4a89-a1cc-9cebcf0122ca.png">

**Comment by lesquoyb** [comment]
Great insight, I didn't notice, thanks. Last commit fixed the shortcut and the splash screen icon. It will be available in the next release
