### ISSUE TITLE
Strange behaviour in list concatenation

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3437]
**Describe the bug**
When running this code:
```
list<list<int>> l2 <- [[2]];
l2 <- l2 + 3;
write l2;
```
the output is `[[2],3]` which is unexpected given that the type of `l2` is `list<list<int>>` so the result should have been something like `[[2],[3]]` or `[[2,3]]`

**Comment by benoitgaudou** [comment]
My 2  cents:
The following one makes perfect sense to me (not that I do not specify the type of the list elements)
```
list l2 <- [[2]];
l2 <- l2 + 3;
write l2;    // displays [[2],3]
```

In the case of a list of list of  int, I have the feeling that the behavior should not be ddifferent, but with a  warning or an execution error to express that this concatenation is not really expected.

**Comment by AlexisDrogoul** [comment]
@benoitgaudou your example is correct, because you do not specify the contents type of the list. Otherwise, what should apply is the casting of the element into a list, as described by @lesquoyb . Moreover, we should have the same behaviour whether we use : 
```gaml
		list<list<int>> l1 <- [[2]];
		l1 << 3;
		write l1;
```

or

```gaml
		list<list<int>> l2 <- [[2]];
		l2 <- l2 + 3;
		write l2;
```

(note the warning in the first -- this is unfortunately extremely quite complicated to do for operators...). 
I've committed a fix for it. Please test !

**Comment by AlexisDrogoul** [comment]
I added the warning to the operator as well and tested in many cases -- seems to work.
