### ISSUE TITLE
TCP Connection Server-Client 

### ISSUE THREAD

**Issue by Beam291** [gama-platform/gama.old#3444]
**Is your request related to a problem? Please describe.**
I have a problem with the 14/6 update on GAMA, the TCP connection at the time of the new update requires the server must have a message sent from a client first, and then the server will send a message to the client. It will become a problem if a case needs the server to send the message first to the client without the need for the client to send the message first.

**Describe the improvement you'd like**
What I want to propose is that the GAMA can let the server send the message to the client without the need for the client sends the message first.

**Comment by hqnghi88** [comment]
Hi,
For networking of Server-Client, there is no CLIENT if there is no request to connect from a specific client. So SERVER send to CLIENT first is no meaning. 
What you describe is a common mailbox that server just put anonymous messages, then any other late coming, check that mailbox. It is broadcasting.

**Comment by lesquoyb** [comment]
I think what he meant is without a defined `to` facet, the sender should broadcast to all the connected clients. It was the case before but changed now that we can send messages to specific client with `tcp_server` protocol

**Comment by hqnghi88** [comment]
Hi, in that case, i think (not test yet) the classical syntax still work, with subscribe, and send to group mailbox. 
BUT it is a feature of gama, when you use with an external application, it's always TCP and it requires handshake. Anyway, the mqtt is there for the broadcasting with external application, as it has the mailbox itself.

**Comment by lesquoyb** [comment]
So if I understand correctly, we can broadcast a message to all the connected clients, but only if they are other gama agents, not  with external applications ? 
I'm almost certain that it used to work with TCP before, is it a big development to make it work again now ?

**Comment by hqnghi88** [comment]
Hi,
"I'm almost certain that it used to work with TCP before, is it a big development to make it work again now ?"
For what i discovered and fixed in the recent commit, the last 3 years version of TCP is single thread server socket, it can have only 1 connected client on network level (that what Patrick have discover so), So i am pretty SURE that you can not have ALL ( > 1 ) external client that receive the broadcasted message. A ambiguous thing in the example model of gama is that it create 2 agent server and 2 agent client, but in fact at the network level, it has only 1 TCP serversocket and 1 connected client, all the agent in gama simulation send and receive through a gama mailbox mechanism with only 1 TCP connection.    
 
"So if I understand correctly, we can broadcast a message to all the connected clients, but only if they are other gama agents, not with external applications ?"
Yes, in the past, if you have 1 gama connected to 1 gama, it can play as multi-client agent (with only 1 tunnel by tcp connection) . with an external app, without the gama messagebox mechanism, with a pure/raw tcp it will stuck with only 1 connection to gama.

With the current version, tcp is now multi-thread, it can have multiple connected client at network level.  
For your question, it is the redundant with what mqtt is implemented for. We can redo in pure tcp connection but it woule have a challenge with the load balancing, managing channels....
And once again for the original issue of this thread, if the requirement is broadcasting/ publish-subscribing, i recommend to use mqtt or if you have a simple model to show the requirement, i can help with some trick in tcp.

**Comment by lesquoyb** [comment]
Ok thank you for the insight, I understand a lot better how/why it used to work now. I think we can manage that in pure gaml as long as the clients send at least one message we can maintain a list of all connected clients and just send to all of them the message we want to broadcast, or switch to mqtt as you suggested.
Closing it as there is no real need for that feature, it would just have been a nice addition but workarounds are good enough

**Comment by hqnghi88** [comment]
Yes i agree that sending to all well-connected client is a need. I think the subscribe channel in gaml works well but i did not test with multi external app yet.
