### ISSUE TITLE
Plugin models folder not automatically refresh after installing plugin

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3445]
**Is your request related to a problem? Please describe.**
When installing a plugin from GAMA's GUI, after restarting the software, the Plugin folder (orange one in explorer) ain't refreshed automatically and doesn't display new folder of the freshly installed plugin. 

This can be fixed by manually refreshing the workspace after the restart.

**Describe the improvement you'd like**
It would be better if the workspace can be automatically refresh (or just the plugin folder) after the restart needed after installing a plugin

**Additional context**
This behavior can be experienced with the experimental plugin QRCode for instance

**Comment by lesquoyb** [comment]
Not working on the latest alpha on windows

**Comment by AlexisDrogoul** [comment]
I think this behaviour has been fixed some time ago when fixing a problem of refresh at startup. Can you test if it is still happening ?

**Comment by lesquoyb** [comment]
Definitely not working with [this](https://github.com/gama-platform/gama/releases/tag/1.9.0) release. Are you referring to more recent changes ?

**Comment by lesquoyb** [comment]
update: thanks to the latest commit from @ptaillandier I was able to make a new release this morning and the problem is still there

**Comment by lesquoyb** [comment]
I think I spotted what was the problem: there's a a workspace refresh done when you install a plugin, but it's done concurrently with the plugin installation, so chances are high that it finishes refreshing before the plugin is even finished downloaded
![image](https://user-images.githubusercontent.com/6374469/221460166-6c7095e8-2e73-4d66-9c83-8ced7f501e09.png)
So if we could chain it with the installation instead of running parallel it should fix the problem

**Comment by AlexisDrogoul** [comment]
Should be solved by now. Reopen in case it still doesn't refresh in the 1.9.1 release.
