### ISSUE TITLE
Meta-data for required plugin (or invisible pragma) of GAML syntax

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3468]
**Is your request related to a problem? Please describe.**
Trying to have dynamic installation plugins/features , i have problem with finding the right plugin that provide the extensions of GAML syntax

**Describe the improvement you'd like**
For example, with a standard GAMA , when we edit the model that use extensions syntax (R, netcdf, Gaming, launchpad....) , an error syntax occurs ("xxx was not declared"). But we cant know which is/are the plugins need to be installed.

**Describe alternatives you've considered**
Some information should have , as "declared in ..... plugin" or even a quick fix with lead to the installation of that plugin.

**Comment by AlexisDrogoul** [comment]
There was once an implementation that allowed that (emitting errors when the required plugins were not present), but it was heavily relying on the metadata in the workspace, something that will probably not be useful in your case as you rely on textual files. So the only practical solution I see is : 

1. At compilation time, establish the list of plugins necessary for the compilation of the model. 
2. Document this list as a pragma (i.e. #requires [...]).
3. Write it to the model file(s) when they are saved. 
4. ? Make sure that the standard GAML editor does not display it ? <== not sure about this one
5. Process the pragma when it exists, making sure the plugins are installed and otherwise raising an early error

This will not provide an individual information on each primitive/variable, etc. as this information would be too costly to save and too large to put in a text file. But it will provide enough information, I think...

@hqnghi88 your thoughts ?

**Comment by hqnghi88** [comment]
Dear Alexis,
Yes, i agree that it is heavy with an addition to each element everywhere. So yes, in the first time, if we can have somewhere, invisible pragma or even a config file, it could be great.
Thank you.

**Comment by AlexisDrogoul** [comment]
To be clearer, the pragma will be visible in the text file, probably like this : 

![Image 2022-08-07 19-17-18](https://user-images.githubusercontent.com/579256/183290204-334aeecc-2ddf-4470-b26a-00a35ae9fc35.png)

or

<img width="411" alt="New Model1 gaml - Gama (runtime) 2022-08-07 19-20-42" src="https://user-images.githubusercontent.com/579256/183290272-50e4e266-fa10-4364-8a5d-b9cc9eafbcb3.png">

**Comment by hqnghi88** [comment]
In fact, the command to install take the name of feature (group of plugins), ie, instead of msi.gama.core it should know to install ummisco.gama.feature.core . So i wonder if eclipse can provide this information from your 2 proposal or not? however it is something developers must specify if there is no way to findout in bundles manager.

**Comment by AlexisDrogoul** [comment]
I have a proof of concept working well with the plugins (not really with the features, though, but I keep digging, as I might retrieve this information from the Equinox Platform); only concern is that hiding the pragma in the editor is really complicated...

**Comment by hqnghi88** [comment]
Should we hiding them? I think it is not very important to hide as it is a accepted syntax like other pragma or include statement?
or Folded block by default is possible?

**Comment by AlexisDrogoul** [comment]
OK. I obtain something like this (automatically added and updated every time you compile a model, which means every time you edit it): 

<img width="378" alt="Statistic Operators gaml - Gama (runtime) 2022-08-11 10-21-28" src="https://user-images.githubusercontent.com/579256/184059809-9e61f556-239f-4a4f-b8d6-90ee69e442c9.png">

We might want to eliminate the "core" plugins (those distributed by default with GAMA), maybe ?

**Comment by hqnghi88** [comment]
the msi.gama.core, yes, but for me , if this metadata exists, i think we can base on the minimum gama (no core.extensions installed by default), they can be install when needed also from gama p2 repository?

**Comment by hqnghi88** [comment]
And "every time edit" you mean any typing in or just when we save model? It should only when we save the modifications, yes?

**Comment by AlexisDrogoul** [comment]
Models are compiled continuously. The overhead added is negligible (just browsing through the AST to get information). So every time you type something, the information is updated 

![screencast 2022-08-11 11-13-07](https://user-images.githubusercontent.com/579256/184063738-f1deca44-b17b-4009-bb3d-aabd75f37619.gif)

**Comment by AlexisDrogoul** [comment]
So -- time to make a decision now. Should we install this feature or no (i.e. both adding the metadata / pragma to the files and verifying the presence of plugins at compile time) ? As a matter of fact, it can also be controlled by a preference, but allowing it to be turned off a little bit defeats the purpose ...

**Comment by hqnghi88** [comment]
Dear Alexis,
I prefer to implement it in 1.8.2, and with the pref off by default, we will have time to decide and find solution to the non-computer scientist after that.

**Comment by AlexisDrogoul** [comment]
One possible issue about this: display extensions are also included in the requirements (as regular plugins), which means we would get an error if running in a headless environment. Should we simply emit a warning in that case ? 

EDIT: but how do we know a missing plugin is a "display" plugin if we do not load it ? 🤔

**Comment by AlexisDrogoul** [comment]
Since I fixed #3485 , I realised that we have the possibility to save some metadata inside the projects. Not as efficient as putting it in the files, but it could maybe host a folder where we would have a file per plugin, with some information on the plugin (update site, etc.) + the list of model files inside this project that require it. And we could also save some information like whether it is a display plugin (since when we save it, we can know if this plugin possesses the `display` extension). 

Do you think it would be worse saving the information there (and, consequently, not in the model file itself) ?

**Comment by lesquoyb** [comment]
Hello, how is this issue going ? Is the initial enhancement request fulfilled ?

**Comment by AlexisDrogoul** [comment]
I close this issue for now on. The `gama.pref_required_plugins` and `gama.pref_missing_plugins` preferences should be set to true for it to be functional.
