### ISSUE TITLE
Warnings with the thread skill and other agents

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama.old#3488]
**Describe the bug**
When the thread skill is used when there are agents (a grid for example), a warning appear sometimes during the execution of the model:  'at cycle 1724: Agents stack is empty, in write 'current time: ' + #now ;'

**To Reproduce**
Run the following model:
```

model testThread

global skills: [thread]{
	init {
		//if there is one, stop the existing thread
		do end_thread;
			
		//create and start a new thread - the runnable_action model will be activated continuously every 10ms
		do start_thread continuous: true interval: 100;
	}
	
	reflex behavior {
		write sample(cycle);
	}
	
	//the action that will be concerned by the new thread
	action runnable_action {
		write "current time: " + #now;
	}	
}

grid cell width: 100 height: 100;

experiment run_a_thread autorun: true;
```

**Desktop (please complete the following information):**
 - OS: Windows
 - GAMA version: 1.8.2 git

**Comment by AlexisDrogoul** [comment]
It happens when a scope is considered as "closed" (ie. the stack of agents to run is empty). I havent looked at the implementation, but maybe it is necessary to create a new scope per thread created -- or more probably each time the runnable_action is executed ? Otherwise, if all threads use the same scope, this kind of behaviour is unavoidable.
