### ISSUE TITLE
Value of parameter not displayed correctly in GUI simulation

### ISSUE THREAD

**Issue by phiola** [gama-platform/gama.old#3493]
**Describe the bug**
When the initial value of a parameter is set by a user defined function/action, it is not displayed in the list of parameters of the simulation, even though it has the correct value.
**To Reproduce**
1. Run this code:
```
model parameters_1

global {
    int param <- set_number(3);
   
    int set_number(int num) {
        return num;
    }
   
   
}    
experiment parameters_1 type: gui {
    parameter "Test" var: param;
    /** Insert here the definition of the input and output of the model */
   
    output {
    }
}
```
2. Look at the parameters.
3. Parameter "Test" should show value `3`, but shows `0`.
4. In the interactive console you can verify, that the variable `param` actually has the value `3`.

**Expected behavior**
The correct value of the parameter should be displayed.

**Screenshots**
![](https://user-images.githubusercontent.com/84175028/192998171-926c8256-8900-4cb1-8009-154bb9b0f96d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - GAMA version: 1.8.2
 - Java version: 17.0.3

**Comment by AlexisDrogoul** [comment]
This issue, as well as #3494 , is now fixed in my opinion. The problem was that the initial value of the parameter was determined by calling a function which was defined only in the model (i.e. the simulation), not accessible by the experiment. So it means that the initialisation should only use general operators/actions, constants, or functions declared in the experiments. The compiler now correctly detects such situations and emits an error. Please test this solution and close the issue if this works for you.
