### ISSUE TITLE
Initial value of parameter not set when using facet "among"

### ISSUE THREAD

**Issue by phiola** [gama-platform/gama.old#3494]
**Describe the bug**
Setting the initial value of a parameter that uses the `among`-facet with a user-defined action/function results in the function not being called. Instead, the parameter is assigned the first value in the list of possible values. Using an internal function (for example `rnd`) works without an issue.
**To Reproduce**
1. Run this code:
```
model parameters_2

global {
	int param <- set_number(3);
	
	int set_number(int num) {
		write "Called";
		return num;
		
	}
	
	
}	
experiment parameters_2 type: gui {
	parameter "Test" var: param among: [1,2,3,4,5];
	/** Insert here the definition of the input and output of the model */
	
	output {
	}
}
```
2. If the function `set_number` would have been called, it would have printed "Called" in the console.
3. You can verify that the variable `param` does not have the expected value 3.

**Expected behavior**
The function `set_number` should be called.

**Desktop:**
- OS: Fedora 36
- GAMA version: 1.8.2
- Java version: 17.0.3

**Comment by AlexisDrogoul** [comment]
This issue, as well as #3493 , is now fixed in my opinion. The problem was that the initial value of the parameter was determined by calling a function which was defined only in the model (i.e. the simulation), not accessible by the experiment. So it means that the initialisation should only use general operators/actions, constants, or functions declared in the experiments. The compiler now correctly detects such situations and emits an error. Please test this solution and close the issue if this works for you.
