### ISSUE TITLE
Gama RC2 with a JDK needs a JDK on Mac OS

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3503]
**Describe the bug**
I have to install GAMA on a new Mac from Scracth. When downloading the GAMA_with_JDK I don't know why when I launch GAMA  it's asking me to install a JDK...

With a pop up window saying "To use Java command-line tools you need to install a JDK"

Is it possible that the last release have a problem or is it only me? Did someone try to install the last RC2 on a new Mac without a JDK?

So not a big deal as by installing the JDK (19) it's working but I think it's an issue no?

**Comment by RoiArthurB** [comment]
@agrignard Very strange behavior that you're describing there... From what we did test (including the RC2 since its release), we never had any similar problem :/

Can you try to double-check that you downloaded the good file.dmg? 🤷 Without any extra information, I'll have to close it as not reproducible...

**Comment by agrignard** [comment]
Yep very strange indeed and it was also the first time for me that it happened. (but it did)

The only thing I know is that it was on a mac mini and the first file I downloaded was the without JDK (that's why it was asking me to download the JDK) and then when i redownloaded the one with JDK I kept having the message saying that I need to install a JDK (which I did) when launching GAMA.

I guess we can close this issue as it's hard to reproduce and it requires a brand new computer (or removing JDK etc)
