### ISSUE TITLE
Operator to parse a JSON string as a map

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3560]
**Is your request related to a problem? Please describe.**
Following discussion #3539 on the mail list, some users need to transform a string (in a JSON format)coming from a message/network communication into a GAMA map to manipulate it. 
As it is possible to read a JSON file and transform it into a GAMA map, it seems that we have everything in GAMA to implement an operator transforming a string into a map.
e.g. : 
`'{"people3": "Festungsbahn Talfahrt XML", "people5": "Final"}'` 
into 
`map(["people3"::"Festungsbahn Talfahrt XML", "people5"::"Final"])`

**Comment by AlexisDrogoul** [comment]
I have quickly added this case to the `map` casting operator. The output is the same as the one in Json files : if you feed it with a direct map it will output this map, otherwise it will output a map with a unique key named `"contents"`, under which the result of the parsing is stored. If the string is malformed, it will raise an exception. 
To summarize:

- `write map('{"key1" "AA, "key2": 100}');` ==> Exception
- `write map('{"key1": "AA", "key2": 100}');` ==> `map(['key1'::'AA','key2'::100])`
- `write map('["key1": "AA", "key2": 100]');` ==> `map(['key1'::'AA','key2'::100])`
- `write map('[{"key1": "AA", "key2": 100}]');` ==> `map(['contents'::[map(['key1'::'AA','key2'::100])]])`

**Comment by lesquoyb** [comment]
I tested the cast to map and it works, I added the reverse operator `as_json_string` that transforms a map or a list into a json string. Please test
