### ISSUE TITLE
In 3d displays, layer superposition causes rendering issues

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3610]
**Describe the bug**
When running an experiment with a 3d display, some elements may be blinking/suddenly disappearing or show strips on them.
I managed to find a model where I can reproduce that issue: `City escape.gaml`. When the water starts overlapping with buildings on the bottom, some of them disappear:
![bandicam 2023-02-09 09-32-45-758](https://user-images.githubusercontent.com/6374469/217704516-d69fd32c-6468-45a3-ac80-9f324dcaf9b9.gif)

If you move the camera around you can observe more rendering issues:
![ezgif com-optimize](https://user-images.githubusercontent.com/6374469/217705593-f56d741a-69b4-497d-b549-05030e0d51e7.gif)

**Additional context**
On windows 11, 100% scaling and on gama from git

**Update**
Turning off the `Add a small increment to the z ordinate of objects to fight visual artefacts` option solves the disappearing of some buildings, but not all the stripes we observe when doing rotations around the map

**Comment by agrignard** [comment]
This is a well known Computer Graphics topic called z fighting https://en.wikipedia.org/wiki/Z-fighting

This is basically when 2 geometry  are drawn on the same plan the renderer as some difficulty to choose which on to choose. Some improvement and work has been done now few years ago (see for instance https://github.com/gama-platform/gama/issues/2222 for the most recent and this one https://github.com/gama-platform/gama/issues/516 for one of the very first time it was raised). Most of the time the order in which you declare your species will give the priority to the geometry "drawn" in last but still some issue can remain

If I am not wrong we use to have a preference to set z-fighting to true/false but I don't find it anymore

**Comment by AlexisDrogoul** [comment]
There is actually nothing we can do completely automatically to solve this z-fighting problem -- and it won't be fixed as it is clearly model-dependent. The preference `Add a small increment to the z ordinate of objects to fight visual artefacts` normally helps by computing a vertical "gap" between objects at the same level, but there are situations where it cannot compute correctly the increment to apply to this gap (and sometimes even makes things worse). Of course -- and hopefully -- there are workarounds that can be applied in each model:

1. Apply a small increment to the layer exhibiting problems, e.g. `species building position: {0,0,0.001};` in the definition of the display;
2. Apply a depth when drawing the objects, e.g. `draw shape color: #gray border: #black depth: 1;` in the aspect of buildings;
3. Try the same with other objects (like `hazard`here). 
4. Reverse the order of the layers (when it makes sense of course). 

In any case, I think it is better to let the modeler choose the best strategy rather than trying to automate things too much. 
I will therefore close this issue (but probably we should document these strategies for fighting the "same z" issue...).
