### ISSUE TITLE
Binary operator (sort_by) can accept more operands

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3619]
**Describe the bug**

It seems possible to use the `sort_by` operator with more than 2 operands whereas it is supposed to accept only 2.
Example given, the following code compiles and can be executed, whereas sort_by is used with 3 operands (1 on left , and 2 on the right in parentheses.

```
my_test <- ["My_Agent[0]"::15.0, "My_Agent[2]"::10.0, "My_Agent[1]"::10.0];
write "my_test-after-sort: " + my_test.pairs collect (each.key::each.value) **sort_by**(each.value, each.key);
```

**Expected behavior**
A compilation error should appear on the `sort_by` operator

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git
 - Java version: 17

**Comment by AlexisDrogoul** [comment]
It was the case for all iterators, actually, as they only considered the first expression. I committed the fix already (together with a better determination of the type of `pairs`. Note that it could be technically possible to enable several arguments to sort_by (in order to have several sorting keys), but let's keep it for another evolution...
