### ISSUE TITLE
Red square Thumbnail on mac os

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3654]
**Describe the bug**
When using the last release 1.9 i notice that the thumbnail on the app (ones launch or using cmd+tab) is a red square

**To Reproduce**
Open GAMA check the thumbnail in the open App or using cmd+tab

**Expected behavior**
Gama thumbnail

**Screenshots**
<img width="230" alt="Screenshot 2023-03-07 at 14 23 10" src="https://user-images.githubusercontent.com/3928502/223436863-a898f87a-7893-4879-a5ae-72c51ec22b44.png">

**Desktop (please complete the following information):**
 - Mac OS Montery
 - Macbook M1

**Comment by AlexisDrogoul** [comment]
Probably a small problem regarding the branding icons -- either a script that does not copy them because they have changed place in the latest commits (makes @RoiArthurB mad !) or maybe they need to be in a certain place (like `msi.gama.application` and not in `ummisco.gama.ui.shared` as they are now). However, I'm a bit surprised because I thought that the macOS version was using the one here : https://github.com/gama-platform/gama/tree/GAMA_1.9.0/ummisco.gama.product/launcher_icons, but maybe they only use it for the app icon ? Maybe we can try to put the icons back (and change the .product to point to them again) like some commits ago (e.g. https://github.com/gama-platform/gama/tree/f9bc0e5028e65c3ccce05eb5d1632f739e777ca8/msi.gama.application/branding_icons)

**Comment by RoiArthurB** [comment]
Strange, this icon for MacOS has the path `/ummisco.gama.product/launcher_icons/icon.icns` (from [gama.product](https://github.com/gama-platform/gama/blob/GAMA_1.9.0/ummisco.gama.product/gama.product#L73)) which hasn't been updated for some years and isn't related to the svg icon generation 🤔🤔🤔

**Comment by lesquoyb** [comment]
It's the same with the windows icons, even when running from eclipse. 
I remember working on the icons for the windows installer and the rules for the .ico file content are pretty strict and not really documented, so maybe it's just old icons that have been optimized or slightly modified and are now invalid ?

**Comment by AlexisDrogoul** [comment]
It seems that the icon for the app and the icon for the tray are two different things. Does the latest update change anything ?

**Comment by lesquoyb** [comment]
running this morning's release I didn't notice any difference, it seems like all the gama icons are broken: tray, app icon, even the small one in the menu to show the about gama ![image](https://user-images.githubusercontent.com/6374469/223622685-2bb05e05-3332-4dd1-aaee-e78293909e66.png)

**Comment by agrignard** [comment]
Same issue with the last release [Alpha Version 1.9.0 (d5abd14f)](https://github.com/gama-platform/gama/releases/tag/1.9.0)

**Comment by AlexisDrogoul** [comment]
Latest release is ok (at last) on this issue. At least on macOS. I close it but feel free to reopen if the tray / dock icon is still undefined.
