### ISSUE TITLE
Cannot excute function "count" when some agents are dead

### ISSUE THREAD

**Issue by leenr01** [gama-platform/gama.old#3664]
**Describe the bug**
When there are agents dying throughout the simulation (using do die statement), many functions result in an error as they try to consider dead agents as well. One example is the "count" function.

**To Reproduce**
1. Go to Library models -> tutorials -> predator prey -> models -> model 6
2. Add "monitor "n" value: prey count(each.color=#blue);" to the end of the code with the other monitor statements and run the code.
3. See error "Cannot evaluate color as the target agent is dead".

**Expected behavior**
I would expect such functions to still operate but only on alive agents. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/120193559/224822710-c85956f4-f5f2-45ff-af9a-b086ccdda425.PNG)

**Desktop:**
 - OS: Windows 10 
 - PC Model: 64 bit
 - GAMA version: 1.8.2

**Additional context**
The function count and other similar ones are crucial in the study of some models and this is a major error.

**Comment by AlexisDrogoul** [comment]
Hi,

The only way I could reproduce this error is by stating in the preferences that simulations should schedule their agents in parallel. Is it your case ? Otherwise it might also be a bug in 1.8.2 that we have corrected since then. 
<img width="477" alt="Monosnap 2023-03-14 08-17-25" src="https://user-images.githubusercontent.com/579256/224867434-004e3c09-3c54-4355-9090-d22c5a658314.png">

At least in GAMA 1.9.0, it works flawlessly. 

If you are in parallel mode (and this might also work on 1.8.2 if there is a specific bug), while it is quite natural to have this kind of error because of the absence of synchronisation between the different processes (management of populations, UI, etc.), you have two ways to prevent it from happening. 

The first it to make sure you are not counting dead agents at the time of the counting:
```
monitor "n" value: (prey where !dead(each)) count(each.color=#blue);
```

The second is to make sure that the outputs are synchronised with the simulations, so that the management of populations, etc. is always done before the UI is updated (and not while it is updated). 
```
	output synchronized: true {
                ...
		monitor "n" value: prey count(each.color=#blue);
	}
```

Tell me how this works for you !
Cheers
Alexis

**Comment by leenr01** [comment]
Thank you very much. 
Yes, disabling the parallel exception in both agents and simulations prevented the error.
