### ISSUE TITLE
Hovering for semantic documentation produces black box

### ISSUE THREAD

**Issue by phiola** [gama-platform/gama.old#3752]
**Describe the bug**
Hovering over a symbol in the code editor to show documentation only produces a black box. 

**To Reproduce**
1. Open any model in the code editor
2. Hover over any keyword in the code
3. See error

**Expected behavior**
The box should contain the documentation of the selecterd keyword/symbol, as described [here](https://gama-platform.org/wiki/ValidationOfModels#semantic-documentation).

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/84175028/231708915-fdff231d-c6ca-47ef-8766-9eaa3d8c2a5a.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - GAMA version: 1.9
 - Java version: 17.0.6
 - Graphics cards / Display system: Intel i5-1240p-Graphics / Wayland

**Comment by RoiArthurB** [comment]
Hello @phiola 

Your issue isn't related to GAMA but to wayland (and/or xwayland). 

The way it does behave is that every screen space not directly printed on your screen (as part of GAMA under the documentation box) will automatically turns black (unloaded). You can see the same behavior happening on Zoom if you share your screen, the participant floating box while be black on the shared screen.

Here's the behavior working well on x11

![Peek 2023-04-13 18-19](https://user-images.githubusercontent.com/16764085/231743349-def29c20-ae06-4167-bfe7-8441aa8ec39f.gif)

I'm sorry we can't fix this and I can only recommand you either to force using x11 (maybe with `xwayland` if not already) or wait for this issue to be fixed by wayland :/
