### ISSUE TITLE
[GS] Runtime errors are not sent back to the client

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.old#3758]
related to #3756 

Python wrapper not reporting model errors. This seems to be true only for missing files. 
missing or undeclared variables are reported. 

for example the following file if missing from the path, is not reported from the server to the client

`file map_init <- image_file("../includes/data/raster_map.png");`

**Comment by lesquoyb** [comment]
After some investigation, in gama server it seems like this error doesn't move the simulation to a state where it's dead nor raises any exception, so the server is stuck in a loop where it steps over a model that does nothing. Should be the same for every kind of client.

**Comment by lesquoyb** [comment]
After some investigation, turns out this example was a special case of a more general problem: runtime errors are not sent to the client.

here is an example model:
```
model runtime

global {
	
	
	reflex i {
		int j <- 1/0;
	}
}

experiment a;
```
If you run it through server there's no error message sent back to the client when the division by zero happen
the special case is that when it happens at init (before init block in that case), it is not even reported into gamaserver console
