### ISSUE TITLE
Opening a gama file with and empty display results in an Xtext validation error

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3785]
**Describe the bug**
Open a Gama file with an empty display block. An error message appear, the experiment button is missing, and the editor cannot interprate Gaml syntax.
![image](https://user-images.githubusercontent.com/18676913/232184523-c95bdc95-67b4-475d-96bd-929d68c881d4.png)

This bug does not appear on 1.8.2. Also uncommenting the lines in the empty display prevent the error.

Here is the code that causes the bug:

```
/***
* Name: volcanotoymodel
* Author: Tri
* Description: 
* Tags: Tag1, Tag2, TagN
***/

model volcanotoymodel

global{
	
}


experiment main type: gui {
	float minimum_cycle_duration <- 0.00001#s;
	output {
		display Nw axes: true{
			species grain aspect: Nw;
		}
		display pores axes: true autosave: every(20#cycle) synchronized: false {
		//	species cell aspect: base;
		}
	}
}
```

 - OS: Windows 10
 - GAMA version: 1.9

**Comment by RoiArthurB** [comment]
The problem in you model is that the species "grain" isn't coded anywhere and you're not importing any other gaml model. So, as displayed in red in GAMA, your model has errors and can't compile.

The fact that your model compiled on 1.8.2 was a bug (letting you run a broken uncompilable model) and this bug is now fixed on GAMA 1.9 :) Otherwise you might unfortunatly removed an `import` line at the beginning of this file creating this normal error.

In both cases, I'm closing this issue as it's not one :)
