### ISSUE TITLE
Online documentation is broken in gama

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3804]
**Describe the bug**
With gama 1.9.1 on windows 11, when opening the online documentation (Help -> GAMA documentation) the rendering of the page is nothing like the website:
![image](https://user-images.githubusercontent.com/6374469/236404704-af7cc8ec-e4dc-42ed-8351-c90764bd9844.png)
some links even open internet explorer instead of opening in a new tab (btw ie is not my default browser)

**Comment by RoiArthurB** [comment]
Works well on Linux

![image](https://user-images.githubusercontent.com/16764085/236731840-c3432612-d9c5-4155-ac86-639a00087d0e.png)

---

EDIT: The problem doesn't come from the website but comes from IE 11 which is deprecated for years and doesn't support new web technology (as React on our website). So the solution should be to move away (in some way) from IE usage

**Comment by RoiArthurB** [comment]
Reference : The feature of switching from IE to Edge has been requested since 2018 ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=538991 ) but is still lacking default activation. The main problem comes from Edge should be implemented with WebView2, but it's neither installed by default, nor packaged within Eclipse yet ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=575660 ); therefore, IE is still opened as fallback.

@lesquoyb is Eclipse/GAMA opening with embedded Edge browser when WV2 is installed?
