### ISSUE TITLE
Problem importing a geotif : not projected

### ISSUE THREAD

**Issue by tbrochier** [gama-platform/gama.old#3818]
**Describe the bug**
When trying to import a geotif, the projection information are not imported, thus we cannot know the longitude/latitude at each point of the space.

**To Reproduce**

1 - download this file : https://dropsu.sorbonne-universite.fr/s/mriDsKEaTaeTQfE
2 - import it in Gama

**Expected behavior**
for each cell we should know the lat/lon so that distance can be computed

**Screenshots**

![image](https://github.com/gama-platform/gama/assets/25725549/153a431f-4364-4fcb-b623-6b996c38b1c6)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Catalina 10.15.5]
 - GAMA version: 1.9.2

**Comment by AlexisDrogoul** [comment]
Looking at the file in QGis, it seems in fact that no projection is associated with it. Maybe adding one in Qgis could help ? I let @ptaillandier handle this !

**Comment by ElCep** [comment]
It's strange because in QGIS on my side it's in WGS84. Do I need to create a projection file for the geotiffs? I've seen that I can do this in gdal with : `gdal_translate -co "TFW=YES" in.tif out.tif` see in https://filesender.renater.fr/?s=download&token=26d27d26-f341-41eb-852d-cc91ec8f0a6a

**Comment by ElCep** [comment]
@ptaillandier it doen't work with my gdal test

**Comment by ptaillandier** [comment]
Hi all,

The geotif files do have a coordinate system, and it's WGS84. However, one
of GAMA's current limitations is that it only works in cartographic
coordinate systems (i.e. projected in meters). So, whenever unprojected
data are used, GAMA projects them on the fly, either with the reference
coordinate system (the one of the shapefile used to define the world's
geometry), or by looking for a UTM projection that is right for the area.
The problem is that GAMA version 1.9.1 is currently unable to project
raster data. So it can't do anything right with your geotiff in WGS84. The
only current solution is to project the geotiff in a cartographic
coordinate system using QGIS or any other software you like, and this
should do the trick (I've tested it on my computer and it seems to work).
Note that all these limitations will be removed with GAMA 2.0 (but
development has only just begun).

Cheers,

Patrick

Le mer. 31 mai 2023 à 23:54, Etienne DELAY ***@***.***> a
écrit :

**Comment by ElCep** [comment]
Ok ! thank you @ptaillandier  ! I'm going to transform all this into UTM zone 28 then! Good luck with version 2! It will be great

**Comment by ElCep** [comment]
I reprojected the raster files with  :
`gdalwarp inFile.tif outFile.tif -t_srs EPSG:32628`
and vectors data with : 
`ogr2ogr -f "ESRI Shapefile" -t_srs EPSG:32628 -s_srs EPSG:4326 outFile.shp inFile.shp`
and it seems to work  ! Thanks  @ptaillandier and [GDAL/OGR](https://gdal.org/) tools
