### ISSUE TITLE
All views in Gama become unresponsive when switching to other windows/applications

### ISSUE THREAD

**Issue by phiola** [gama-platform/gama.old#3843]
**Describe the bug**
Gama becomes unresponsive after a short while when switching to other windows.

**To Reproduce**
1. Open Gama
2. Verify that everything is usable
3. Change to other window/application
4. Switch back to Gama
5. All views are unresponsive, only the menu on the top of the window still works. It's still possible to close Gama as usual.

**Expected behavior**
Gama should still be responsive.

**Screenshots**

[Gama_unresponsive.webm](https://github.com/gama-platform/gama/assets/84175028/18732c45-e0f0-43f5-b5eb-ce00b4eb0065)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - GAMA version: 1.9.1 with JDK
 - Java version: 17.0.6
 - Graphics cards / Display system: Intel Graphics, Wayland

**Additional context**
I am using [this](https://gama-platform.org/wiki/Troubleshooting#workaround-if-opengl-display-crash-gama) workaround to use Gama. Could this problem be related?

**Comment by RoiArthurB** [comment]
Hello,

This issue is very complicated to fix without more logs than your video. However, as explained in the troubleshoot that you linked, it is known that GAMA doesn't work with Wayland and you should run it using x11/xwayland (it is done with the env var `GDK_BACKEND`). 

I don't know how you installed/run GAMA on your system, but you can try this command and see if the issue remains : `GTK_THEME=Adwaita GDK_BACKEND=x11 /path/to/gama-platform/Gama`

Also, as your issue seems to be related to SWT (the library in charge of GUI), maybe you can check if comments on this similar issue can help you https://github.com/eclipse-platform/eclipse.platform.swt/issues/158
