### ISSUE TITLE
[HEADLESS] Have separated headless wrapper for release w/ and w/o JDK for Linux/MacOS

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3866]
**Is your request related to a problem? Please describe.**
Currently there are (at least?) two different headless scripts generated for windows: one for the version with jdk and one for the version without. There's absolutely no difference in the content of the scripts (apart from the version number that someone forgot to bump in w/o jdk).
I think it's a factor of confusion, and as the script itself takes into account the presence or not of a jdk folder, there's no point keeping two scripts.

**Describe the improvement you'd like**
Merge the two scripts into one

**Comment by RoiArthurB** [comment]
Updating this issue : The problem wasn't major for Windows (same script catching both cases copied 2 times in the source), but the problem is more major for Linux and MacOS which have 2 different scripts with only difference the java call.

**Solution prefered**
Having a single script per os (preferably the one in `product/extraresources`) which can be used in both release. This will eliminate every headless scripts in `travis/` and have to update the `travis/zip_withjdk.sh` which was replacing those scripts. (hello @WoodenMaiden :) )
