### ISSUE TITLE
facet 'accumulate_values' for 'data' (in charts) prevent time series from being drawn

### ISSUE THREAD

**Issue by tnguyenh** [gama-platform/gama.old#3918]
**Describe the bug**
When using the facet 'accumulate_values' for 'data' when trying to draw some charts: if the value is set to true, the time series is drawn without accumulation. Setting the value to false prevent the time series from being drawn.

**To Reproduce**
Use the following model:

````
model accu

experiment exp type: gui {
	output {
		display  chart  {
			chart name: 'test' type: series  {
				data legend: 'test' value: 1 accumulate_values: false;
			}
		}
	}
}
````

Without the facet accumulate_values, the curve is drawn normally (flat curve with value 1). With the facet to true, the same curve is drawn, instead of accumulation. If the facet is set to false, only the first point is drawn.

 - GAMA version: 1.9.2

**Comment by AlexisDrogoul** [comment]
It seems that this facet (the purpose of which I do not really understand, but it's another matter) will either take into account all the x,y values of the dataset (incl. the ones previously added, like it is the case by default in series) or only the last y value (like in pie charts, I guess ?).

The result you obtain is then "normal" : either a line at y = 1 or a single point. The only issue here is the x-value; which doesn't seem to change. I have changed that (now the "new x" is displayed instead of the first one), hoping it will help close this issue.
